services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:80"
    volumes:
      - .:/app
      - /app/bin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Host=db;Port=5432;Database=quizdb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
